### ISSUE TITLE
Stuck on no instance for `KnownSymbol`

### ISSUE THREAD

**Issue by magthe** [cdsmith/HMock#1]
This isn't so much an issue as a request for help.

I have the following

```
import Data.ByteString.Lazy (ByteString)
import Network.Wreq qualified as W

class Monad m => MonadHttpClient m where
  mHttpGet :: String -> m (W.Status, ByteString)
  mHttpPost :: W.Postable a => String -> a -> m (W.Status, ByteString)
```

which I attempt to write two simple tests for. The first, for `mHttpGet`, works fine:

```
import Test.HMock
import Test.HMock.TH (makeMockable)
import Test.Tasty
import Test.Tasty.HUnit

makeMockable ''MonadHttpClient

httpGetTest :: TestTree
httpGetTest = testCase "Get Test" $ do
  (s, b) <- runMockT $ do
    expect $ MHttpGet "url" |-> (status200, "")
    mHttpGet "url"
  s @=? status200
  b @=? "c"
```

The second, for `mHttpPost`, won't type check, and I don't know how to solve it:

```
httpPostTest :: TestTree
httpPostTest = testCase "Post Test" $ do
  (s, b) <- runMockT $ do
    expect $ MHttpPost "url" ("hello" :: ByteString) |-> ()
    mHttpPost "url" ("hello" :: ByteString)
  s @=? status200
  b @=? "a"
```

The errors are

```
test/HttpTest.hs:44:5: error:
    • No instance for (GHC.TypeLits.KnownSymbol name0)
        arising from a use of ‘expect’
    • In a stmt of a 'do' block:
        expect $ MHttpPost "url" ("hello" :: ByteString) |-> ()
      In the second argument of ‘($)’, namely
        ‘do expect $ MHttpPost "url" ("hello" :: ByteString) |-> ()
            mHttpPost "url" ("hello" :: ByteString)’
      In a stmt of a 'do' block:
        (s, b) <- runMockT
                    $ do expect $ MHttpPost "url" ("hello" :: ByteString) |-> ()
                         mHttpPost "url" ("hello" :: ByteString)
   |
44 |     expect $ MHttpPost "url" ("hello" :: ByteString) |-> ()
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

test/HttpTest.hs:44:14: error:
    • No instance for (Expectable
                         cls0
                         name0
                         IO
                         ()
                         (Action
                            MonadHttpClient
                            "mHttpPost"
                            b0
                            (Network.HTTP.Types.Status.Status, ByteString)))
        arising from a use of ‘|->’
    • In the second argument of ‘($)’, namely
        ‘MHttpPost "url" ("hello" :: ByteString) |-> ()’
      In a stmt of a 'do' block:
        expect $ MHttpPost "url" ("hello" :: ByteString) |-> ()
      In the second argument of ‘($)’, namely
        ‘do expect $ MHttpPost "url" ("hello" :: ByteString) |-> ()
            mHttpPost "url" ("hello" :: ByteString)’
   |
44 |     expect $ MHttpPost "url" ("hello" :: ByteString) |-> ()
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm not at all sure what this even means, but I'm guessing it's related to the `Postable a` constraint in some way.

Any help and/or insights would be very helpful.

**Comment by magthe** [comment]
I'm using version 0.1.0.1 of the library, and GHC 8.10.4.

**Comment by cdsmith** [comment]
Ah, yes, that's an ugly error message.  It's the second error that is relevant here.  In order to use `expect $ MHttpPost ...`, you need `MHttpPost` to have an `Expectable` instance.  `makeMockable` generates such an instance only if `mHttpPost` is simple enough.

The solution is to expect with a `Matcher` instead of an `Action`.  That looks something like this: `expect $ MHttpPost_ (eq "url") anything |-> ()`.  The `anything` can be replaced by a more specific predicate, must it must match the rank-2 type `forall a. W.Postable a => Predicate a`.  In other words, it must be able to be interpreted for any argument type.  If `W.Postable` is a subclass of `Typeable`, then you could use the `typed` predicate to only match calls where the argument is a `ByteString`.  Doing so requires `Typeable`, though, since it means HMock needs to inspect the type of the argument at runtime.  That's just not possible in Haskell without `Typeable`.

**Comment by magthe** [comment]
Switching to a `Matcher` made it work with `anything` but in the end I think I'll go for adding the `Typeable a` as that simplifies writing those predicates quite a bit.

Thanks for the help!

**Comment by cdsmith** [comment]
Thanks for the question.  I've added https://github.com/cdsmith/HMock/blob/main/README.md#why-does-ghc-complain-about-no-instance-for-expectable--action- to the readme file.

**Comment by cdsmith** [comment]
I have fixed this error message in HEAD, and it'll be much nicer in the next release.

**Comment by magthe** [comment]
Very nice! I've been pushing on, trying out HMock to replace some of the tests I have where I in the past have used custom monad stacks for testing purposes. So far it's a pleasure to work with.
