### ISSUE TITLE
HMock assumes stable hashing

### ISSUE THREAD

**Issue by TomMD** [cdsmith/HMock#20]
Due to the recent dust-up over hash collisions and Aeson DOS, I tried turning on +random-initial-seed in hashable 1.3.0.0 only to find my HMock fail. The implication is that HMock is depending on stable hashing (though I can't fully rule out that it is something else in my code).

Looking at HMock the use of hashable are via monotraversable unlift-io and constraints.  I have yet to narrow the issue down further.

**Comment by TomMD** [comment]
I tried the unit tests in hmock and the four libraries between it and hashable with the flag. None of those tests could reproduce my issue so I'm closing this until I can narrow things down further.

**Comment by cdsmith** [comment]
Okay, let me know if you can reproduce anything.

**Comment by TomMD** [comment]
Three problem was very much mine and obvious once I saw a mock with hard coded bytestring result that was an encoded JSON object.
