### ISSUE TITLE
GHC 9.2.1 support

### ISSUE THREAD

**Issue by TravisCardwell** [cdsmith/HMock#27]
I am using HMock and `explainable-predicates` with GHC 9.2.1 without issue, using `allow-newer` configuration to ignore the upper bound constraints on the `base` and `template-haskell` dependencies.  I investigated bumping these constraints so that the next releases will work without the `allow-newer` configuration.

The HMock tests all pass with GHC 9.2.1 with the following changes:

```diff
diff --git a/HMock.cabal b/HMock.cabal
index 54dbab8..4982c80 100644
--- a/HMock.cabal
+++ b/HMock.cabal
@@ -42,7 +42,7 @@ library
                       Test.HMock.Internal.Step,
                       Test.HMock.Internal.TH,
                       Test.HMock.Internal.Util
-    build-depends:    base >=4.11.0 && < 4.16,
+    build-depends:    base >=4.11.0 && < 4.17,
                       constraints >= 0.13 && < 0.14,
                       containers >= 0.6.2 && < 0.7,
                       data-default >= 0.7.1 && < 0.8,
@@ -53,7 +53,7 @@ library
                       mtl >= 2.2.2 && < 2.3,
                       stm >= 2.5.0 && < 2.6,
                       syb >= 0.7.2 && < 0.8,
-                      template-haskell >= 2.14 && < 2.18,
+                      template-haskell >= 2.14 && < 2.19,
                       transformers-base >= 0.4.5 && < 0.5,
                       unliftio >= 0.2.18 && < 0.3,
     hs-source-dirs:   src
```

The following changes also need to be made:

- [ ] `HMock.cabal` - Update `explainable-predicates` upper bound if necessary
- [ ] `.travis.yml` - Update `ghc`
- [ ] `HMock.cabal` - Update `tested-with`
- [ ] `README.md` - Update "Which GHC versions are supported?"
- [ ] `CHANGELOG.md` - Add entry?

**Comment by cdsmith** [comment]
I've released a new version that fixes this.
