### ISSUE TITLE
Superclass requirement is painful(`Missing MockT instance for a superclass.`)

### ISSUE THREAD

**Issue by TomMD** [cdsmith/HMock#28]
With HMock 3 it used to be possible to write (pseudo Haskell):

```
class (MonadError Bar m) => MonadFoo m where ...
makeMockable ''MonadFoo
```

These days trying to do the same thing with HMock 5 we write:

```
class (MonadError Bar m) => MonadFoo m where ...
makeMockable [t|MonadFoo|]
```

Which yields

```
Missing MockT instance for a superclass.
```

Which is really unfortunate. MockT isn't named `MockM`. Sometimes it is useful to write a mock test as `runErrorT $ runMockT $ ...`.  Is this use just a defunct case that is supported through other means?

**Comment by cdsmith** [comment]
This was not an intentional change!  I am looking into it.

**Comment by cdsmith** [comment]
It looks like the problem here is that `Test.HMock.Internal.TH.simplifyContext` fails on constraints that use `FlexibleContexts`.  For example, adding `MonadUnliftIO` or something else without a literal type in it.  The problem is that `all isTypeVar args` is the wrong termination condition.

**Comment by cdsmith** [comment]
I've released a new version with this fix.

**Comment by TomMD** [comment]
Thanks Chris!
