### ISSUE TITLE
GHC 9.4.2 support

### ISSUE THREAD

**Issue by TravisCardwell** [cdsmith/HMock#31]
As with [GHC 9.2.1 support][], I am using HMock and `explainable-predicates` with GHC 9.4.2 without issue.  The HMock tests all pass with GHC 9.4.2 with the following changes:

[GHC 9.2.1 support]: <https://github.com/cdsmith/HMock/issues/27>

```diff
diff --git a/HMock.cabal b/HMock.cabal
index 703f588..397b71f 100644
--- a/HMock.cabal
+++ b/HMock.cabal
@@ -42,7 +42,7 @@ library
                       Test.HMock.Internal.Step,
                       Test.HMock.Internal.TH,
                       Test.HMock.Internal.Util
-    build-depends:    base >=4.11.0 && < 4.17,
+    build-depends:    base >=4.11.0 && < 4.18,
                       constraints >= 0.13 && < 0.14,
                       containers >= 0.6.2 && < 0.7,
                       data-default >= 0.7.1 && < 0.8,
@@ -53,7 +53,7 @@ library
                       mtl >= 2.2.2 && < 2.3,
                       stm >= 2.5.0 && < 2.6,
                       syb >= 0.7.2 && < 0.8,
-                      template-haskell >= 2.14 && < 2.19,
+                      template-haskell >= 2.14 && < 2.20,
                       transformers-base >= 0.4.5 && < 0.5,
                       unliftio >= 0.2.18 && < 0.3,
     hs-source-dirs:   src
```

The following changes also need to be made:

* [ ] `HMock.cabal` - Update `explainable-predicates` upper bound if necessary
* [ ] `.github/workflows/ci.yml` - Update `jobs.cabal.strategy.matrix.ghc`
* [ ] `HMock.cabal` - Update `tested-with`
* [ ] `README.md` - Update "Which GHC versions are supported?"
* [ ] `CHANGELOG.md` - Add entry?

On a related note, HMock is working with GHC 9.2.4 as well.  You might want to update the tests and documentation to use it instead of GHC 9.2.3.

**Comment by cdsmith** [comment]
Thanks!  Done, and will upload to Hackage as soon as CI passes
